name: VASIL
channels:
  - defaults
dependencies:
  - python
  - numpy
  - scipy
  - openpyxl
  - pandas
  - matplotlib
  - seaborn
  - joblib
  - regex
  - pip
  - pyOpenSSL
  - patsy
  - scikit-learn
  - pip:
    - voila
    - ipywidgets
    - widgetsnbextension
    - mpl_axes_aligner
